services:
  django:
    image: courseoverflow/django
    container_name: courseoverflow_django
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - courseoverflow
    depends_on:
      - postgres
    env_file:
      - ./server/.env
  # command: >
  #   sh -c "python manage.py makemigrations &&
  #          python manage.py migrate &&
  #          python manage.py collectstatic --noinput &&
  #          python manage.py runserver 0.0.0.0:8000"
  #
  postgres:
    image: postgres:latest
    container_name: courseoverflow_postgres
    ports:
      - "5432:5432"
    networks:
      - courseoverflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./server/.env

networks:
  courseoverflow:
    driver: bridge

volumes:
  postgres_data:
    driver: local
