version: '3.8'
services:
  apache:
    image: httpd:2.4
    container_name: courseoverflow_apache
    ports:
      - "80:80"
    volumes:
      - ./apache:/usr/local/apache2/conf
    networks:
      - courseoverflow
    depends_on:
      - react
      - django

  react:
    image: courseoverflow/react
    container_name: courseoverflow_react
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
    networks:
      - courseoverflow
    depends_on:
      - django
    env_file:
      - ./client/.env

  django:
    image: courseoverflow/django
    container_name: courseoverflow_django
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
    networks:
      - courseoverflow
    depends_on:
      - postgres
    env_file:
      - ./server/.env

  postgres:
    image: postgres:13
    container_name: courseoverflow_postgres
    networks:
      - courseoverflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  courseoverflow:
    driver: bridge

volumes:
  postgres_data:
    driver: local