version: "3.8"
services:
  react:
    image: courseoverflow/react
    container_name: courseoverflow_react
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
    networks:
      - courseoverflow
    depends_on:
      - django
    env_file:
      - ./client/.env

  django:
    image: courseoverflow/django
    container_name: courseoverflow_django
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
    networks:
      - courseoverflow
    depends_on:
      - postgres
    env_file:
      - ./server/.env

  postgres:
    image: postgres:latest
    container_name: courseoverflow_postgres
    networks:
      - courseoverflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  courseoverflow:
    driver: bridge

volumes:
  postgres_data:
    driver: local
